import {REPO,uid,emptyAlbum,newTrip,newStop,escapeHTML as h,validateAlbum,publicAlbum,allPhotos,moveItem,makeZip,readZip,MAX_EXPORT_BYTES} from './core.mjs';
import {loadDraft,saveDraft,getPhoto,putPhoto,importDraft,fetchPublished,preparePhoto} from './storage.js';
import {AtlasMap} from './map.js';
const root=document.querySelector('#app'),modal=document.querySelector('#modal'),modalBody=document.querySelector('#modal-body');
let published=emptyAlbum(),draft=null,mode='places',tripId='',stopId='',map=null,editing=false,preview=false,busy=false,saveTimer,saveChain=Promise.resolve(),saveError=null,selectedCity=null,searchResults=[],downloadUrl=null,returnFocus=null;
const photoURLs=new Map();
const sample={id:'sample',title:'在瑞士，沿着湖与山',start:'2026-08-07',end:'2026-08-13',note:'这是一段演示旅程，展示地图、路线和手账的浏览方式。发布自己的第一段旅行后，示例会自动消失。',published:true,stops:[
  {id:'sg',city:'日内瓦',country:'瑞士',lat:46.2044,lng:6.1432,date:'2026-08-07',note:'从湖边开始的一程。',transport:'火车',photos:[]},
  {id:'sb',city:'伯尔尼',country:'瑞士',lat:46.948,lng:7.4474,date:'2026-08-09',note:'慢慢走过老城的街道。',transport:'火车',photos:[]},
  {id:'sl',city:'卢塞恩',country:'瑞士',lat:47.0502,lng:8.3093,date:'2026-08-12',note:'把湖光山色，夹进这一页。',transport:'火车',photos:[{id:'sample-photo',file:'lucerne.jpg',caption:'卢塞恩湖 · 示例照片 / Andrew Bossi',date:''}]},
  {id:'sz',city:'苏黎世',country:'瑞士',lat:47.3769,lng:8.5417,date:'2026-08-13',note:'在下一次出发前，留一段回忆。',transport:'火车',photos:[]}
]};
const localCities=[['东京','Tokyo','日本',35.6762,139.6503],['大阪','Osaka','日本',34.6937,135.5023],['京都','Kyoto','日本',35.0116,135.7681],['昆明','Kunming','中国',25.0389,102.7183],['北京','Beijing','中国',39.9042,116.4074],['上海','Shanghai','中国',31.2304,121.4737],['苏黎世','Zurich','瑞士',47.3769,8.5417],['日内瓦','Geneva','瑞士',46.2044,6.1432],['洛桑','Lausanne','瑞士',46.5197,6.6323],['伯尔尼','Bern','瑞士',46.948,7.4474],['卢塞恩','Lucerne','瑞士',47.0502,8.3093],['因特拉肯','Interlaken','瑞士',46.6863,7.8632],['劳特布伦嫩','Lauterbrunnen','瑞士',46.5935,7.9091],['米伦','Murren','瑞士',46.5594,7.8927],['布拉格','Prague','捷克',50.0755,14.4378],['维也纳','Vienna','奥地利',48.2082,16.3738],['布达佩斯','Budapest','匈牙利',47.4979,19.0402],['斯德哥尔摩','Stockholm','瑞典',59.3293,18.0686],['塔林','Tallinn','爱沙尼亚',59.437,24.7536],['赫尔辛基','Helsinki','芬兰',60.1699,24.9384],['帕尔马','Palma','西班牙',39.5696,2.6502],['伦敦','London','英国',51.5074,-.1278],['巴黎','Paris','法国',48.8566,2.3522],['爱丁堡','Edinburgh','英国',55.9533,-3.1883],['罗马','Rome','意大利',41.9028,12.4964],['阿姆斯特丹','Amsterdam','荷兰',52.3676,4.9041],['纽约','New York','美国',40.7128,-74.006],['悉尼','Sydney','澳大利亚',-33.8688,151.2093]];
const $=s=>root.querySelector(s);
const activeTrip=()=>draft?.trips.find(t=>t.id===tripId);
const activeStop=()=>activeTrip()?.stops.find(s=>s.id===stopId);
const dateRange=t=>[t.start,t.end].filter(Boolean).join(' — ')||'日期待记录';
const tripPhotos=t=>t.stops.flatMap(s=>s.photos);
const displayPhoto=p=>h(photoURLs.get(p.file)||'./'+p.file);
function toast(message){const box=document.querySelector('#toast');box.textContent=message;box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,5500);}
function showModal(html){returnFocus=document.activeElement;modalBody.innerHTML=html;if(!modal.open)modal.showModal();modal.querySelector('.close').focus();}
function closeModal(){modal.close();if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null;}returnFocus?.focus?.();}
modal.querySelector('.close').onclick=closeModal;
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
modal.addEventListener('cancel',()=>{if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null;}});
function confirmAction(title,body,callback){showModal(`<h2>${h(title)}</h2><p>${h(body)}</p><div class="dialog-actions"><button class="secondary" id="cancel-action">取消</button><button class="primary" id="confirm-action">确认</button></div>`);modalBody.querySelector('#cancel-action').onclick=closeModal;modalBody.querySelector('#confirm-action').onclick=()=>{closeModal();callback()};}
function destroyMap(){map?.destroy();map=null;}
function saveStateSoon(){clearTimeout(saveTimer);const indicator=$('#save-status');if(indicator)indicator.textContent='正在保存到此设备…';saveTimer=setTimeout(()=>flushSave().catch(()=>{}),400);}
function flushSave(){clearTimeout(saveTimer);if(!draft)return Promise.resolve();const snapshot=structuredClone(draft);saveChain=saveChain.catch(()=>{}).then(()=>saveDraft(snapshot)).then(()=>{saveError=null;const label=$('#save-status');if(label)label.textContent='已保存到此设备 · 请定期下载备份';}).catch(e=>{saveError=e;const label=$('#save-status');if(label)label.textContent='本机保存失败，请立即下载备份';toast('本机空间不足或浏览器限制存储，请立即下载备份。');throw e;});return saveChain;}
async function hydratePhotos(album){for(const p of allPhotos(album)){if(photoURLs.has(p.file))continue;const blob=await getPhoto(p.file);if(blob)photoURLs.set(p.file,URL.createObjectURL(blob));}}
function photoCard(p,index,edit=false){return `<div class="photo-card">${edit?`<img src="${displayPhoto(p)}" alt="${h(p.caption||'旅行照片')}" loading="lazy"><label>照片说明<input data-photo-field="caption" data-id="${p.id}" value="${h(p.caption)}" maxlength="1000" placeholder="写一句照片说明"></label><label>拍摄日期<input type="date" data-photo-field="date" data-id="${p.id}" value="${h(p.date)}"></label><div class="photo-tools"><button data-photo-move="${index}" ${index===0?'disabled':''}>${index===0?'本站封面':'前移 ↑'}</button><button data-photo-remove="${p.id}">移出</button></div>`:`<button data-photo="${index}"><img src="${displayPhoto(p)}" alt="${h(p.caption||'旅行照片')}" loading="lazy"><span>${h(p.caption)}</span></button>`}</div>`;}
function openPhotos(photos,index=0){if(!photos.length)return;const p=photos[index];showModal(`<h2>${h(p.caption||'旅行照片')}</h2><p class="muted">${h(p.date)} · ${index+1} / ${photos.length}</p><img class="light-photo" src="${displayPhoto(p)}" alt="${h(p.caption||'旅行照片')}"><div class="dialog-actions spread"><button id="previous-photo" ${index===0?'disabled':''}>← 上一张</button><button id="next-photo" ${index===photos.length-1?'disabled':''}>下一张 →</button></div>`);modalBody.querySelector('#previous-photo').onclick=()=>openPhotos(photos,index-1);modalBody.querySelector('#next-photo').onclick=()=>openPhotos(photos,index+1);}
modal.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')modalBody.querySelector('#previous-photo:not(:disabled)')?.click();if(e.key==='ArrowRight')modalBody.querySelector('#next-photo:not(:disabled)')?.click()});
function openJournal(t){showModal(`<p class="eyebrow">TRAVEL JOURNAL${t.id==='sample'?' · 示例':''}</p><h2>${h(t.title)}</h2><p class="muted">${h(dateRange(t))}</p><p class="journal-note">${h(t.note)}</p>${t.stops.map((s,i)=>`<section class="journal-stop"><div class="stop-heading"><b>${String(i+1).padStart(2,'0')}</b><div><h3>${h(s.city)}</h3><small>${h(s.date)} · ${h(s.country)}</small></div><span>${i?h(s.transport):''}</span></div><p class="journal-note">${h(s.note)}</p><div class="photo-grid">${s.photos.map((p,j)=>`<button class="journal-photo" data-journal-stop="${i}" data-journal-photo="${j}"><img src="${displayPhoto(p)}" alt="${h(p.caption||s.city)}" loading="lazy"><span>${h(p.caption)}</span></button>`).join('')}</div></section>`).join('')}`);modalBody.querySelectorAll('[data-journal-stop]').forEach(b=>b.onclick=()=>openPhotos(t.stops[Number(b.dataset.journalStop)].photos,Number(b.dataset.journalPhoto)));}
function renderPublic(){
  destroyMap();editing=false;document.querySelector('#edit-link').textContent=preview?'返回整理 ↗':'整理相册 ↗';
  let album=published;try{if(preview)album=publicAlbum(draft)}catch(e){preview=false;toast(e.message);location.hash='edit';return;}
  const demo=!album.trips.length,shown=demo?[sample]:album.trips,trip=shown.find(t=>t.id===tripId)||shown[0];const all=shown.flatMap(t=>t.stops),points=mode==='journeys'?trip.stops:all;const active=points.find(s=>s.id===stopId)||points.find(s=>s.photos.length)||points[0];
  const matches=active?(mode==='journeys'?[active]:all.filter(s=>s.city===active.city&&Math.abs(s.lat-active.lat)<.05&&Math.abs(s.lng-active.lng)<.05)):[];const photos=matches.flatMap(s=>s.photos);
  root.innerHTML=`${preview?'<div class="notice"><strong>本机预览</strong> · 尚未更新公开网站。<button data-action="back-edit">返回整理</button></div>':''}<section class="heading"><div><p class="eyebrow">A PERSONAL TRAVEL ATLAS</p><h1>走过的地方，<span>留下的时光。</span></h1></div><div class="stats"><span><b>${new Set(all.map(s=>s.city)).size.toString().padStart(2,'0')}</b>个地点</span><span><b>${shown.length.toString().padStart(2,'0')}</b>段旅程</span><span><b>${all.reduce((n,s)=>n+s.photos.length,0).toString().padStart(2,'0')}</b>张照片</span></div></section>
  <section class="atlas"><div class="map-side"><div class="map-toolbar"><div class="tabs" role="group" aria-label="地图模式"><button data-mode="places" aria-pressed="${mode==='places'}">◎ 我的足迹</button><button data-mode="journeys" aria-pressed="${mode==='journeys'}">⌁ 旅行路线</button></div><small>双指缩放 · 轻点地点</small></div><div id="atlas-map" class="map-host"></div><div class="map-bottom"><span>● ${mode==='journeys'?'站点顺序 · 行程示意':'去过的地方'}</span><span>${demo?'示例预览 · 非个人旅行记录':'照片与文字 © 海晨'}</span></div></div>
  <aside class="memory"><div class="memory-cover">${photos[0]?`<img src="${displayPhoto(photos[0])}" alt="${h(active.city)}">`:'<div class="empty-photo">这一站，等待照片</div>'}<span>${demo?'SAMPLE / 示例':'A MOMENT TO KEEP'}</span></div><div class="memory-body"><p class="eyebrow">${h(active?.country||'')} / ${h(mode==='journeys'?active?.date:'地点相册')}</p><h2>${h(active?.city||'第一段旅行')}</h2><p class="memory-note">${h(active?.note||'照片里的风景，和当时的心情。')}</p><p class="muted">${photos.length} 张照片 · ${matches.length} 次停留</p>${photos.length?'<button class="primary full" data-action="open-photos">翻开相册 ↗</button>':''}<div class="stops-list">${(mode==='journeys'?trip.stops:points.filter((s,i,a)=>a.findIndex(p=>p.city===s.city)===i)).map((s,i)=>`<button data-stop="${h(s.id)}" class="${s.id===active?.id?'active':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${h(s.city)}</span><small>${mode==='journeys'?h(s.date):''}</small></button>`).join('')}</div></div></aside></section>
  <section class="journeys"><div class="section-heading"><div><p class="eyebrow">THE JOURNAL</p><h2>一程，一本手账</h2></div><span>${demo?'先看看手账会是什么样子':'按旅程，收藏沿途的故事'}</span></div><div class="trip-grid">${shown.map((t,i)=>{const p=tripPhotos(t)[0];return `<article class="trip-card"><button class="trip-cover" data-route="${h(t.id)}">${p?`<img src="${displayPhoto(p)}" alt="${h(t.title)}" loading="lazy">`:'<div class="empty-photo">旅行手账</div>'}<span>JOURNEY ${String(i+1).padStart(2,'0')}</span>${demo?'<em>示例旅程</em>':''}</button><div class="trip-body"><p class="eyebrow">${h(dateRange(t))}</p><h3>${h(t.title)}</h3><p class="muted">${h(t.stops.map(s=>s.city).join(' → '))}</p><div class="trip-actions"><button data-route="${h(t.id)}">查看路线</button><button data-journal="${h(t.id)}">翻阅手账 ↗</button></div></div></article>`}).join('')}${demo?'<div class="start-card"><p class="eyebrow">YOUR NEXT CHAPTER</p><h3>下一页，写你的旅行。</h3><p>选照片、填城市。<br>没有定位信息，也能点亮地图。</p><a href="#edit">开始整理第一段旅程 ↗</a></div>':''}</div>${demo?'<p class="credits">示例照片：<a href="https://commons.wikimedia.org/wiki/File:6617-6618_-_Vitznau_-_Vierwaldst%C3%A4ttersee.jpg" target="_blank" rel="noreferrer">Andrew Bossi / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/2.5/" target="_blank" rel="noreferrer">CC BY-SA 2.5</a> · 已缩放，展示时裁切</p>':''}</section>`;
  map=new AtlasMap($('#atlas-map'),{stops:points,route:mode==='journeys',fit:mode==='journeys',onSelect:s=>{stopId=s.id;renderPublic()}});
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderPublic()});root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{tripId=b.dataset.route;stopId='';mode='journeys';renderPublic();$('#atlas-map').scrollIntoView({behavior:'smooth',block:'center'})});root.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>{stopId=b.dataset.stop;renderPublic()});root.querySelectorAll('[data-journal]').forEach(b=>b.onclick=()=>openJournal(shown.find(t=>t.id===b.dataset.journal)));$('[data-action="open-photos"]')?.addEventListener('click',()=>openPhotos(photos));$('[data-action="back-edit"]')?.addEventListener('click',()=>{location.hash='edit'});
}
async function openEditor(){
  preview=false;editing=true;destroyMap();root.innerHTML='<p class="loading">正在打开此设备的整理空间…</p>';
  try{if(!draft){draft=await loadDraft();if(draft)draft=validateAlbum(draft);else{draft=structuredClone(published);await saveDraft(draft);}await hydratePhotos(draft);}if(!draft.trips.length)draft.trips.push(newTrip());if(!activeTrip())tripId=draft.trips[0].id;if(!activeStop())stopId=activeTrip().stops[0]?.id||'';renderEditor();}catch(e){root.innerHTML=`<div class="empty-state"><h2>暂时无法打开本机草稿</h2><p>${h(e.message)}</p><p>请使用 Safari 普通浏览模式，并确保设备有可用空间。未执行任何清空操作。</p><button onclick="location.reload()">重新尝试</button></div>`;}
}
function field(label,key,value,type='text',level='trip'){return `<label>${label}<input type="${type}" data-${level}-field="${key}" value="${h(value)}" ${type==='text'?'maxlength="150"':''}></label>`;}
function renderEditor(){
  destroyMap();const t=activeTrip(),s=activeStop();if(!t)return;editing=true;document.querySelector('#edit-link').textContent='整理相册 ↗';
  root.innerHTML=`<section class="heading editor-heading"><div><p class="eyebrow">YOUR TRAVEL WORKSPACE</p><h1>把这一程，收进相册。</h1><p class="muted">① 添加城市　② 选择照片　③ 导出　④ 上传 GitHub</p></div><button class="secondary" data-action="help">iPad 发布指南</button></section><div class="notice"><strong>这是此设备的整理空间。</strong> 草稿不会自动上传，也不需要登录。只有用你的 GitHub 账号提交文件，才会更改公开相册。清理 Safari 数据可能删除草稿，请下载备份。</div>
  <div class="editor-layout"><aside class="editor-sidebar"><div class="sidebar-heading"><h2>我的旅程</h2><button data-action="new-trip" aria-label="新建旅程">＋</button></div>${draft.trips.map(x=>`<button class="saved-trip ${x.id===t.id?'selected':''}" data-trip="${x.id}"><span>${h(x.title||'未命名旅行')}</span><small>${x.published?'纳入公开文件':'本机草稿'} · ${x.stops.length} 站</small></button>`).join('')}<div class="backup-tools"><button class="secondary" data-action="backup">下载完整备份</button><button data-action="import">恢复 ZIP 备份</button><button data-action="load-public">载入网站上的相册</button><input id="import-file" type="file" accept=".zip,application/zip" hidden><p>备份包括本机草稿和照片，请保存在 iPad“文件”或 iCloud。</p></div></aside>
  <div class="editor-main"><section class="editor-card"><div class="card-heading"><span>01</span><h2>这一段旅行</h2></div>${field('旅行名称','title',t.title)}<div class="form-row">${field('开始日期','start',t.start,'date')}${field('结束日期','end',t.end,'date')}</div><label>旅行小记<textarea data-trip-field="note" rows="3" maxlength="10000" placeholder="为什么出发？最想记住什么？">${h(t.note)}</textarea></label><label class="check-row"><input type="checkbox" data-trip-field="published" ${t.published?'checked':''}> 将这段旅行纳入公开文件</label><small class="muted">勾选后仍需导出并上传 GitHub 才会公开。</small></section>
  <section class="editor-card"><div class="card-heading"><span>02</span><h2>沿途的城市</h2></div><div class="stop-chips">${t.stops.map((x,i)=>`<div class="stop-chip ${x.id===s?.id?'selected':''}"><button data-edit-stop="${x.id}">${i+1}. ${h(x.city)}</button><button data-move-stop="${i}" data-direction="-1" aria-label="前移${h(x.city)}" ${i===0?'disabled':''}>↑</button><button data-move-stop="${i}" data-direction="1" aria-label="后移${h(x.city)}" ${i===t.stops.length-1?'disabled':''}>↓</button></div>`).join('')}</div><div class="city-search"><label>添加城市<input id="city-query" placeholder="如 卢塞恩 / Lucerne" maxlength="150"></label><button class="secondary" data-action="search-city">查找位置</button></div><div id="city-results"></div><div class="editor-map map-host" id="editor-map"></div><div id="city-confirm" hidden></div><p class="muted small">也可以直接点击地图选点，再填写城市名。城市搜索使用 Open-Meteo / GeoNames。</p></section>
  <section class="editor-card"><div class="card-heading"><span>03</span><h2>${s?h(s.city)+'的照片':'放入旅行照片'}</h2></div>${s?`<div class="form-row">${field('城市名称','city',s.city,'text','stop')}${field('国家 / 地区','country',s.country,'text','stop')}</div><div class="form-row">${field('停留日期','date',s.date,'date','stop')}<label>抵达这一站的交通<select data-stop-field="transport">${['火车','飞机','汽车','轮船','步行','其他'].map(x=>`<option ${s.transport===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>这一站的记忆<textarea data-stop-field="note" rows="3" maxlength="10000">${h(s.note)}</textarea></label><button class="upload-zone" data-action="add-photos"><span>＋</span><strong>选择这一站的照片</strong><small>可多选 · 自动压缩 · 不需要 GPS 定位</small></button><input id="photo-files" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden><p class="muted small">支持 JPEG / PNG / WebP。相机 RAW、iPhone HEIC 请先导出为 JPEG；保留原图另作备份。</p><div id="photo-progress" role="status"></div><div class="edit-photos">${s.photos.map((p,i)=>photoCard(p,i,true)).join('')}</div><button class="text-danger" data-action="remove-stop">移除这一站</button>`:'<div class="empty-state">先添加一个城市，再放入照片。</div>'}</section><button class="text-danger" data-action="remove-trip">从本机草稿移除这段旅行</button></div></div>
  <div class="save-bar"><span id="save-status">已保存到此设备 · 请定期下载备份</span><div><button class="secondary" data-action="preview">预览</button><button class="primary" data-action="export">导出公开文件 ↗</button></div></div>`;
  map=new AtlasMap($('#editor-map'),{stops:t.stops,route:true,fit:!!t.stops.length,onPick:(lat,lng)=>showCity({city:$('#city-query').value.trim(),country:'',lat,lng})});
  root.querySelectorAll('[data-trip-field]').forEach(el=>el.addEventListener('input',()=>{t[el.dataset.tripField]=el.type==='checkbox'?el.checked:el.value;saveStateSoon()}));root.querySelectorAll('[data-stop-field]').forEach(el=>el.addEventListener('input',()=>{s[el.dataset.stopField]=el.value;saveStateSoon()}));root.querySelectorAll('[data-photo-field]').forEach(el=>el.addEventListener('input',()=>{s.photos.find(p=>p.id===el.dataset.id)[el.dataset.photoField]=el.value;saveStateSoon()}));
  root.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>{tripId=b.dataset.trip;stopId=activeTrip().stops[0]?.id||'';renderEditor()});root.querySelectorAll('[data-edit-stop]').forEach(b=>b.onclick=()=>{stopId=b.dataset.editStop;renderEditor()});root.querySelectorAll('[data-move-stop]').forEach(b=>b.onclick=()=>{moveItem(t.stops,Number(b.dataset.moveStop),Number(b.dataset.moveStop)+Number(b.dataset.direction));saveStateSoon();renderEditor()});root.querySelectorAll('[data-photo-move]').forEach(b=>b.onclick=()=>{moveItem(s.photos,Number(b.dataset.photoMove),Number(b.dataset.photoMove)-1);saveStateSoon();renderEditor()});root.querySelectorAll('[data-photo-remove]').forEach(b=>b.onclick=()=>confirmAction('移出这张照片？','将从本机这段旅行中移出；公开网站在你重新发布前不会改变。',()=>{s.photos=s.photos.filter(p=>p.id!==b.dataset.photoRemove);saveStateSoon();renderEditor()}));
  $('[data-action="new-trip"]').onclick=()=>{const x=newTrip();draft.trips.push(x);tripId=x.id;stopId='';saveStateSoon();renderEditor()};$('[data-action="search-city"]').onclick=searchCity;$('#city-query').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();searchCity()}};
  $('[data-action="add-photos"]')?.addEventListener('click',()=>$('#photo-files').click());$('#photo-files')?.addEventListener('change',e=>addPhotos(e.target.files));
  $('[data-action="remove-stop"]')?.addEventListener('click',()=>confirmAction('移除这一站？','这一站的照片和文字会从本机旅行中移出。建议先下载备份。',()=>{t.stops=t.stops.filter(x=>x.id!==s.id);stopId=t.stops[0]?.id||'';saveStateSoon();renderEditor()}));
  $('[data-action="remove-trip"]').onclick=()=>confirmAction('移除这段旅行？','会从本机草稿移除这段旅行。此前公开的内容需再次导出上传后才会从网站消失；GitHub 历史文件仍可能保留。',()=>{draft.trips=draft.trips.filter(x=>x.id!==t.id);if(!draft.trips.length)draft.trips.push(newTrip());tripId=draft.trips[0].id;stopId='';saveStateSoon();renderEditor()});
  $('[data-action="help"]').onclick=showGuide;$('[data-action="backup"]').onclick=()=>exportAlbum(true);$('[data-action="export"]').onclick=()=>exportAlbum(false);$('[data-action="import"]').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>restore(e.target.files[0]);
  $('[data-action="load-public"]').onclick=()=>confirmAction('用网站内容替换本机草稿？','尚未发布的本机修改将被替换。请先下载完整备份。',async()=>{try{await flushSave();const a=await fetchPublished();await saveDraft(a);draft=a;if(!draft.trips.length)draft.trips.push(newTrip());tripId=draft.trips[0].id;stopId='';await hydratePhotos(draft);renderEditor();toast('已载入网站上的相册');}catch(e){toast(e.message)}});
  $('[data-action="preview"]').onclick=()=>{try{publicAlbum(draft);preview=true;location.hash='preview';}catch(e){toast(e.message)}};
}
function showCity(city){selectedCity=city;const box=$('#city-confirm');box.hidden=false;box.innerHTML=`<div class="form-row"><label>城市名<input id="picked-city" value="${h(city.city)}" maxlength="150"></label><label>国家 / 地区<input id="picked-country" value="${h(city.country)}" maxlength="150"></label></div><small>${city.lat.toFixed(3)}, ${city.lng.toFixed(3)} · 可在地图重新选点</small><button class="secondary" id="add-city">＋ 添加这一站</button>`;$('#add-city').onclick=()=>{const name=$('#picked-city').value.trim();if(!name)return toast('请填写城市名');const s={...newStop(name,selectedCity.lat,selectedCity.lng),country:$('#picked-country').value.trim()};activeTrip().stops.push(s);stopId=s.id;saveStateSoon();renderEditor();};}
async function searchCity(){const q=$('#city-query').value.trim();if(q.length<2)return toast('请输入至少两个字符，或直接在地图选点');const button=$('[data-action="search-city"]');button.disabled=true;button.textContent='正在查找…';let local=localCities.filter(c=>c[0].includes(q)||c[1].toLowerCase().includes(q.toLowerCase())).map(c=>({city:c[0],country:c[2],lat:c[3],lng:c[4]}));try{if(!local.length){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:q,count:'10',language:'zh',format:'json'}),{signal:controller.signal});if(!r.ok)throw Error();const d=await r.json();local=(d.results||[]).filter(c=>Math.abs(c.latitude)<=85).map(c=>({city:c.name,country:[c.admin1,c.country].filter(Boolean).join(' · '),lat:c.latitude,lng:c.longitude}));}finally{clearTimeout(timer)}}searchResults=local;$('#city-results').innerHTML=local.map((c,i)=>`<button class="city-result" data-city="${i}">${h(c.city)} <small>${h(c.country)}</small></button>`).join('')||'<p class="muted">未找到结果。试试英文城市名，或直接在地图选点。</p>';root.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{const c=searchResults[Number(b.dataset.city)];showCity(c);map.fit([c]);});}catch{toast('城市搜索暂时不可用，可以直接在地图选点。')}finally{button.disabled=false;button.textContent='查找位置';}}
function setBusy(value){busy=value;root.querySelectorAll('button,input,textarea,select').forEach(el=>{if(value){el.dataset.wasDisabled=el.disabled?'1':'0';el.disabled=true}else if(el.dataset.wasDisabled!==undefined){el.disabled=el.dataset.wasDisabled==='1';delete el.dataset.wasDisabled}});document.querySelector('#view-link').style.pointerEvents=value?'none':'';document.querySelector('#edit-link').style.pointerEvents=value?'none':'';}
async function addPhotos(files){if(!files?.length)return;const stop=activeStop();setBusy(true);let done=0;try{for(const file of files){$('#photo-progress').textContent=`正在处理 ${done+1} / ${files.length}，请保持页面打开…`;const blob=await preparePhoto(file),id=uid(),name='photo-'+id+'.jpg';await putPhoto(name,blob);photoURLs.set(name,URL.createObjectURL(blob));stop.photos.push({id,file:name,caption:'',date:stop.date});await flushSave();done++;}toast(`已保存 ${done} 张照片到此设备`);}catch(e){toast(`已保存 ${done} 张。${e.message}`);}finally{setBusy(false);renderEditor();}}
async function photoBytes(name){const local=await getPhoto(name);if(local)return new Uint8Array(await local.arrayBuffer());const r=await fetch('./'+name);if(!r.ok)throw Error('找不到照片 '+name+'，请恢复备份或重新选择照片');const bytes=new Uint8Array(await r.arrayBuffer());if(bytes[0]!==255||bytes[1]!==216)throw Error('照片文件无法读取，请检查已上传的文件');return bytes;}
async function exportAlbum(backup){
  setBusy(true);try{await flushSave().catch(()=>{});const album=backup?validateAlbum(draft):publicAlbum(draft);const photos=[...new Map(allPhotos(album).map(p=>[p.file,p])).values()];if(!backup&&photos.length>98)throw Error('这一版支持一次导出最多 98 张公开照片，适合 GitHub 网页的一次上传。请先精选照片；更多照片需要扩展分批发布。');const files=[[backup?'draft.json':'album.json',JSON.stringify(album,null,2)]];let total=0;for(let i=0;i<photos.length;i++){const label=$('#save-status');if(label)label.textContent=`准备${backup?'备份':'公开文件'} ${i+1} / ${photos.length}…`;const bytes=await photoBytes(photos[i].file);total+=bytes.length;if(total>MAX_EXPORT_BYTES)throw Error('导出文件超过 90 MB，请减少照片或分开整理');files.push([photos[i].file,bytes]);}const blob=makeZip(files);if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(blob);const name=backup?'travel-album-backup.zip':'travel-album-publish.zip';showModal(`<p class="eyebrow">${backup?'PRIVATE BACKUP':'READY TO PUBLISH'}</p><h2>${backup?'完整备份已准备好':'公开文件已准备好'}</h2><p>${album.trips.length} 段旅行 · ${photos.length} 张照片 · ${(blob.size/1024/1024).toFixed(1)} MB</p>${backup?'<p>包含本机草稿与照片。请保存到“文件”或 iCloud，恢复时直接选择这个原始 ZIP。不要把私人备份上传到公开仓库。</p>':'<p>只包含勾选“纳入公开文件”的旅行。当前网站尚未改变。</p>'}<a class="primary download" href="${downloadUrl}" download="${name}">下载${backup?'完整备份':'公开文件'} ZIP</a>${backup?'':`<ol><li>在 iPad“文件”App 的“下载项”中，轻点 ZIP 解压。</li><li>打开下面的 GitHub 上传页面，选择 <strong>choose your files</strong>。</li><li>进入解压的文件夹，选择里面的 <strong>album.json 和所有 photo-…jpg</strong>；不要上传 ZIP 本身或整个文件夹。</li><li>点击 <strong>Commit changes</strong>，等待网站更新后刷新。</li></ol><a class="secondary" href="${REPO}/upload/main" target="_blank" rel="noreferrer">打开 GitHub 上传页面 ↗</a><p class="muted small">代码文件无需重新上传。照片和 JSON 都放在仓库最外层。同名文件会更新；旧照片文件及历史记录不会自动删除。</p>`}`);
  }catch(e){toast(e.message)}finally{setBusy(false);const label=$('#save-status');if(label)label.textContent=saveError?'本机保存失败，请下载备份':'已保存到此设备 · 请定期下载备份';}
}
async function restore(file){if(!file)return;if(file.size>MAX_EXPORT_BYTES+1024*1024)return toast('备份超过 90 MB，当前版本无法导入');try{const files=readZip(await file.arrayBuffer()),bytes=files.get('draft.json')||files.get('album.json');if(!bytes)throw Error('备份里没有相册资料');const a=validateAlbum(JSON.parse(new TextDecoder().decode(bytes)));const photos=[];for(const p of allPhotos(a)){const b=files.get(p.file);if(!b||b[0]!==255||b[1]!==216)throw Error('备份缺少照片或包含无效照片');photos.push([p.file,new Blob([b],{type:'image/jpeg'})]);}confirmAction('恢复这个备份？',`将用备份中的 ${a.trips.length} 段旅行替换当前本机草稿。网站不会自动改变。`,async()=>{setBusy(true);try{await flushSave();await importDraft(a,photos);draft=a;for(const u of photoURLs.values())URL.revokeObjectURL(u);photoURLs.clear();await hydratePhotos(a);if(!draft.trips.length)draft.trips.push(newTrip());tripId=draft.trips[0].id;stopId='';toast('备份已恢复');}catch(e){toast('恢复失败：'+e.message)}finally{setBusy(false);renderEditor()}});}catch(e){toast(e.message)}}
function showGuide(){showModal(`<h2>在 iPad 上发布相册</h2><ol><li>添加旅行和城市；可点击地图手动定位。</li><li>选中城市，选择照片，可一次多选。</li><li>填写日期和文字，勾选准备公开的旅行。</li><li>点击“预览”检查，再点“导出公开文件”。</li><li>下载 ZIP，到“文件”App 轻点解压。</li><li>在 GitHub 上传解压后的 album.json 和所有照片，提交更新。</li></ol><p>第一版每次支持最多 98 张公开照片、合计 90 MB。建议先用 5～10 张照片熟悉流程。</p><p>草稿只在当前浏览器，定期“下载完整备份”。清理浏览器或更换设备前，先下载备份。</p><p>整理页面本身公开，但其他访客只能改他们自己设备上的副本，不能通过这个页面修改你的 GitHub 仓库。</p><a class="secondary" href="${REPO}/upload/main" target="_blank" rel="noreferrer">GitHub 上传入口 ↗</a>`);}
window.addEventListener('hashchange',()=>{if(busy)return;if(location.hash==='#edit')openEditor();else{if(location.hash!=='#preview')preview=false;renderPublic()}});
window.addEventListener('beforeunload',e=>{if(busy||saveError){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&draft)flushSave().catch(()=>{})});
try{published=await fetchPublished();if(location.hash==='#edit')await openEditor();else renderPublic();}catch(e){root.innerHTML=`<div class="empty-state"><h2>暂时无法加载相册</h2><p>${h(e.message)}</p><button id="reload">重新加载</button><a href="#edit">打开本机草稿</a></div>`;$('#reload').onclick=()=>location.reload();}
